print("-"*40)
print("[ 학생성적프로그램 ]")
print("-"*40)
print("1. 학생성적입력")
print("2. 학생성적전체입력")
print("3. 학생검색")
print("4. 학생성적수정")
print("5. 학생성적삭제")
print("6. 등수처리")
print("0. 종료")
print("-"*40)
choice = input("원하는 번호를 입력하세요.>> ")
choice = int(choice)